USE [master]
GO
/****** Object:  Database [java6_thy]    Script Date: 7/21/2024 7:30:13 PM ******/
CREATE DATABASE [java6_thy]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'java6_thy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\java6_thy.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'java6_thy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\java6_thy_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [java6_thy] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [java6_thy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [java6_thy] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [java6_thy] SET ANSI_NULLS OFF
GO
ALTER DATABASE [java6_thy] SET ANSI_PADDING OFF
GO
ALTER DATABASE [java6_thy] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [java6_thy] SET ARITHABORT OFF
GO
ALTER DATABASE [java6_thy] SET AUTO_CLOSE ON
GO
ALTER DATABASE [java6_thy] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [java6_thy] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [java6_thy] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [java6_thy] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [java6_thy] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [java6_thy] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [java6_thy] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [java6_thy] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [java6_thy] SET  ENABLE_BROKER
GO
ALTER DATABASE [java6_thy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [java6_thy] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [java6_thy] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [java6_thy] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [java6_thy] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [java6_thy] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [java6_thy] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [java6_thy] SET RECOVERY SIMPLE
GO
ALTER DATABASE [java6_thy] SET  MULTI_USER
GO
ALTER DATABASE [java6_thy] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [java6_thy] SET DB_CHAINING OFF
GO
ALTER DATABASE [java6_thy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [java6_thy] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [java6_thy] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [java6_thy] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
ALTER DATABASE [java6_thy] SET QUERY_STORE = OFF
GO
USE [java6_thy]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 7/21/2024 7:30:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
    [id] [int] IDENTITY(1,1) NOT NULL,
    [name] [varchar](50) NOT NULL,
    [email] [varchar](100) NOT NULL,
    PRIMARY KEY CLUSTERED
(
[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
    UNIQUE NONCLUSTERED
(
[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
    USE [master]
    GO
ALTER DATABASE [java6_thy] SET  READ_WRITE
GO
